baseURL = "https://stoicallytyped.com"
languageCode = "en"
title = "StoicallyTyped"
theme = "nuo-fork"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
disqusShortname = "stoicallytyped"

# Google Analytics UA number
googleAnalytics = "UA-45737040-5"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Works"
  weight = 20
  identifier = "works"
  url = "https://github.com/matthewcmckenna"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# [[menu.main]]
#   name = "Resume"
#   weight = 100
#   identifier = "resume"
#   url = "/resume/"

# Add your own params here
[params]
  author = "Matt McKenna"
  bg = "images/grey-prism.svg"
  avatar = "images/avatar.png"
  seotitle = "StoicallyTyped"
  subtitle = "Matt McKenna on Programming: Focusing on Android, Kotlin, Privacy, Opensource, and Keyboards"
  description = "Matt McKenna on Programming, focusing on Android, Kotlin, Privacy, Opensource, and Keyboards"
  paginate = 10

  # Choose your social networks
  email = "mmckenna@pm.me"
  github = "matthewcmckenna"
  twitter = "matthewcmckenna"
  # linkedin = "linkedin_username"
  # weibo = "weibo_username"
  # wechat= "images/qrcode.jpg"  # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  instagram = "matthewcmckenna"
  youtube = "mattcmckenna"
  # vimeo = "vimeo_username"
  medium = "mattmck"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"
  stackoverflow = "11262765"
  # codesandbox = "codesandbox_username"
  # npm = "npm_username"
  reddit = "stoicallytyped"
  twitch = "stoicallytyped"

  # Overrid theme styles in this file
  # customStyle = "styles/custom.scss"

  # Changyan Comments (China Only)
  changyan = false
  # changyanId = "cyt3toRiB"
  # changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "XTs6jWvGXmxXyotmkSW69UAC6NZq0TMOcLhUCArl43Y"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  msValidate = "9D4DECDD3B7D96807C16229579849858"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"

  # ICP Number (China Only)
  # ICP = "苏ICP备16005986号-2"
